### ISSUE TITLE
can't use on odoo v8?

### ISSUE THREAD

**Issue by jaronemo** [asphaltzipper/azi-odoo-modules#10]
Dears:

This module 
can use on odoo v8?

**Comment by matt454357** [comment]
Yes, some modules work on v8.  Which module are you interested in?

**Comment by jaronemo** [comment]
Dears:

mrp_llc

從 Outlookhttp://aka.ms/weboutlook 傳送

---

寄件者: Matt Taylor notifications@github.com
寄件日期: 2016年8月3日 下午 11:46
收件者: asphaltzipper/azi-odoo-modules
副本: Jason; Author
主旨: Re: [asphaltzipper/azi-odoo-modules] can't use on odoo v8? (#10)

Yes, some modules work on v8. Which module are you interested in?

**Comment by matt454357** [comment]
Yes, I believe it will work on v8. Our most recent work has been on v9.

**Comment by matt454357** [comment]
Try the 8.0 branch

**Comment by jaronemo** [comment]
Dears:

Thanks for share this module...

But....when i install this module....

[cid:1fe695be-1318-40f4-89c0-35ffc5030942]

can't use ...

use manually with pgadmin... execute sql  ..is faild...

從 Outlookhttp://aka.ms/weboutlook 傳送

---

寄件者: Matt Taylor notifications@github.com
寄件日期: 2016年8月5日 下午 10:12
收件者: asphaltzipper/azi-odoo-modules
副本: Jason; Author
主旨: Re: [asphaltzipper/azi-odoo-modules] can't use on odoo v8? (#10)

Try the 8.0 branch

**Comment by scosist** [comment]
@jaronemo I believe the mrp_llc module for [v8](https://github.com/asphaltzipper/azi-odoo-modules/tree/8.0/mrp_llc) has a few bugs. I would recommend using the mrp_llc module for [v9](https://github.com/asphaltzipper/azi-odoo-modules/tree/9.0/mrp_llc) module, although it may require modification to run with odoo v8.

**Comment by jaronemo** [comment]
Dears:

So.. use mrp_llc module for v9 ...

install on v8....then fix it , right?

從 Outlookhttp://aka.ms/weboutlook 傳送

---

寄件者: scosist notifications@github.com
寄件日期: 2016年8月7日 下午 04:52
收件者: asphaltzipper/azi-odoo-modules
副本: Jason; Mention
主旨: Re: [asphaltzipper/azi-odoo-modules] can't use on odoo v8? (#10)

@jaronemohttps://github.com/jaronemo I believe the mrp_llc module for v8https://github.com/asphaltzipper/azi-odoo-modules/tree/8.0/mrp_llc has a few bugs. I would recommend using the mrp_llc module for v9https://github.com/asphaltzipper/azi-odoo-modules/tree/9.0/mrp_llc module, although it may require modification to run with odoo v8.

**Comment by matt454357** [comment]
Yes.  And, if you don't mind, do a PR with your changes.
