### ISSUE TITLE
mrp_time_bucket ignores effectivity dates on BOM

### ISSUE THREAD

**Issue by matt454357** [asphaltzipper/azi-odoo-modules#3]
The MRP algorithm should get the BOM that would be effective on the start date of the parent procurement.  Does the _bom_explode() method consider start and stop dates on the mrp.bom.line model?

**Comment by scosist** [comment]
I had made a mental note about testing for this but forgot.

Yes, it does with `_skip_bom_line` but it compares them with `time.strftime(DEFAULT_SERVER_DATE_FORMAT)` so if we override `_skip_bom_line` it should give us what we want, just need to test.
