### ISSUE TITLE
Outbound procurements should always have location_id = production

### ISSUE THREAD

**Issue by matt454357** [asphaltzipper/azi-odoo-modules#5]
The method _prepare_outbound_procurement() creates outbound procurement orders (dependent demand).  These procurement orders should always have the Procurement Location field (location_id) set equal to the Production location.

 I believe the following [line of code](https://github.com/asphaltzipper/azi-odoo-modules/commit/a306a6b1a906bed54158409547936a40885e2c2b#diff-41b81e2fc3dfa08f6679f137c0ab80f4R212) should be changed from:

``` python
'location_id': parent_location_id and parent_location_id.id or product.property_stock_production.id,
```

to:

``` python
'location_id': product.property_stock_production.id,
```

**Comment by scosist** [comment]
The `parent_location_id` uses the `location_src_id` which should be a production location unless it is not defined, in which case it will get the product production location.
